"""empty message

Revision ID: 3d341b407d0d
Revises: d050dd943783
Create Date: 2024-01-28 14:59:03.344912

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3d341b407d0d'
down_revision = 'd050dd943783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testimony', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('APPROVED', 'PENDING', 'REJECTED', name='testimony_status_enum'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testimony', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('APPROVED', 'PENDING', 'REJECTED', name='testimony_status_enum'),
               nullable=True)

    # ### end Alembic commands ###
