"""empty message

Revision ID: 45160b195de9
Revises: 
Create Date: 2024-01-19 23:11:57.809207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45160b195de9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identification_code', sa.String(length=10), nullable=False),
    sa.Column('type', sa.Enum('CAT', 'DOG', name='type_enum'), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('size', sa.Enum('SMALL', 'MEDIUM', 'LARGE', 'EXTRA_LARGE', name='size_enum'), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender_enum'), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('vaccinated', sa.Enum('YES', 'NO', name='yes_no_enum_vaccinated'), nullable=True),
    sa.Column('castrated', sa.Enum('YES', 'NO', name='yes_no_enum_castrated'), nullable=True),
    sa.Column('dewormed', sa.Enum('YES', 'NO', name='yes_no_enum_dewormed'), nullable=True),
    sa.Column('microchip', sa.Enum('YES', 'NO', name='yes_no_enum_microchip'), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('additional_information', sa.String(length=400), nullable=True),
    sa.Column('status', sa.Enum('ADOPTED', 'NOT_ADOPTED', 'PASSED_AWAY', name='status_enum'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identification_code')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('user_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('address', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.Integer(), nullable=True),
    sa.Column('backyard', sa.Enum('YES', 'NO', name='yes_no_enum_backyard'), nullable=True),
    sa.Column('other_pets', sa.String(length=30), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='role_enum'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('animals_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('testimony',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.Column('testimony_text', sa.String(length=400), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('animal_id'),
    sa.UniqueConstraint('image_url')
    )
    op.create_table('adoption_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('testimony_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['testimony_id'], ['testimony.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('animal_id'),
    sa.UniqueConstraint('testimony_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adoption_users')
    op.drop_table('testimony')
    op.drop_table('animals_images')
    op.drop_table('user')
    op.drop_table('animals')
    # ### end Alembic commands ###
