"""empty message

Revision ID: 697785cb28c8
Revises: aff7dbc81708
Create Date: 2024-01-28 17:09:30.568718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '697785cb28c8'
down_revision = 'aff7dbc81708'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adoption_users', schema=None) as batch_op:
        batch_op.alter_column('testimony_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adoption_users', schema=None) as batch_op:
        batch_op.alter_column('testimony_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
