"""empty message

Revision ID: 966b3b2930c3
Revises: 62585f955e6b
Create Date: 2024-01-25 17:25:10.657655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '966b3b2930c3'
down_revision = '62585f955e6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.alter_column('identification_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.alter_column('identification_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    # ### end Alembic commands ###
