"""empty message

Revision ID: d050dd943783
Revises: 741d7591b2ec
Create Date: 2024-01-28 14:56:32.487832

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd050dd943783'
down_revision = '741d7591b2ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('APPROVED', 'PENDING', 'REJECTED', name='testimony_status_enum').create(op.get_bind())
    with op.batch_alter_table('testimony', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', postgresql.ENUM('APPROVED', 'PENDING', 'REJECTED', name='testimony_status_enum', create_type=False), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testimony', schema=None) as batch_op:
        batch_op.drop_column('status')

    sa.Enum('APPROVED', 'PENDING', 'REJECTED', name='testimony_status_enum').drop(op.get_bind())
    # ### end Alembic commands ###
