"""empty message

Revision ID: f4480545e245
Revises: 697785cb28c8
Create Date: 2024-01-29 00:06:16.698707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4480545e245'
down_revision = '697785cb28c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testimony', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adoption_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('testimony_image_url_key', type_='unique')
        batch_op.create_unique_constraint(None, ['adoption_id'])
        batch_op.create_foreign_key(None, 'adoption_users', ['adoption_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testimony', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('testimony_image_url_key', ['image_url'])
        batch_op.drop_column('adoption_id')

    # ### end Alembic commands ###
